### ISSUE TITLE
save signature in DB

### ISSUE THREAD

**Issue by Dani3lSun** [Dani3lSun/apex-plugin-apexsignature#1]
@ehabwagdy here we go...
## Expected behavior

save the signature in DB
## Actual behavior

1- what i should to write in "Save Button JQuery Selector" are button name or in button action select defined by dynamic action or what ?
2- i would to make change in attribute plsql to add my table are replace the following part

```
IF NOT
apex_collection.collection_exists(p_collection_name => l_collection_name) THEN
apex_collection.create_collection(l_collection_name);
END IF;
-- add collection member (only if BLOB not null)
IF dbms_lob.getlength(lob_loc => l_blob) IS NOT NULL THEN
apex_collection.add_member(p_collection_name => l_collection_name,
p_c001 => l_filename, -- filename
p_c002 => l_mime_type, -- mime_type
p_d001 => SYSDATE, -- date created
p_blob001 => l_blob); -- BLOB img content
END IF;
```

with my table

```
INSERT INTO CC.IBS_EMP_SIGNATURE (
IBS_NO, EMP_SIGNATURE, BOSTA_ID) 
VALUES ( 44433/* IBS_NO /,
l_blob/ EMP_SIGNATURE /,
4455 / BOSTA_ID */ );
commit;
```

**Comment by Dani3lSun** [comment]
Hi @ehabwagdy
you can find a demo app with some proper configuration here:
https://github.com/Dani3lSun/apex-plugin-apexsignature/releases/tag/v1.1
This shows how to set the static_id of your buttons and display the signatures in a report...

For saving into your own table I would suggest you to use the events that comes with this plugin.
Create a new Dynamic Action with Event "Signature saved to DB", that executes PL/SQL code which selects the APEX collection into your table, this could look like this:

```
DECLARE
  --
  CURSOR l_cur_signature IS
    SELECT c001    AS filename,
           c002    AS mime_type,
           d001    AS date_created,
           blob001 AS img_content
      FROM apex_collections
     WHERE collection_name = 'APEX_SIGNATURE';
  --
  l_rec_signature l_cur_signature%ROWTYPE;
  --
BEGIN
  -- get original collection from plugin
  OPEN l_cur_signature;
  FETCH l_cur_signature
    INTO l_rec_signature;
  CLOSE l_cur_signature;
  -- insert into own table
  INSERT INTO cc.ibs_emp_signature
    (ibs_no,
     emp_signature,
     bosta_id)
  VALUES
    (44433,
     l_rec_signature.img_content,
     4455);
  -- delete original collection
  apex_collection.delete_collection(p_collection_name => 'APEX_SIGNATURE');
  --
END;
```

So you don´t have to touch and change the original pl/sql code of the plugin...

Hope that helps!

**Comment by ehabwagdy** [comment]
thanks a lot for your support and your effective plugin

**Comment by ehabwagdy** [comment]
Dear Daniel 

thanks to advise me if i want take some value from some text item in insert statement ? 
how i can do that ?

**Comment by ehabwagdy** [comment]
FYI
i changed your code to insert direct in my table

```
DECLARE
  --
  l_collection_name VARCHAR2(100);
  l_clob            CLOB;
  l_blob            BLOB;
  l_filename        VARCHAR2(100);
  l_mime_type       VARCHAR2(100);
  l_token           VARCHAR2(32000);
  --
BEGIN
  -- get defaults
  l_filename  := 'signature_' ||
                 to_char(SYSDATE,
                         'YYYYMMDDHH24MISS') || '.png';
  l_mime_type := 'image/png';
  -- build CLOB from f01 30k Array
  dbms_lob.createtemporary(l_clob,
                           FALSE,
                           dbms_lob.session);

  FOR i IN 1 .. apex_application.g_f01.count LOOP
    l_token := wwv_flow.g_f01(i);

    IF length(l_token) > 0 THEN
      dbms_lob.writeappend(l_clob,
                           length(l_token),
                           l_token);
    END IF;
  END LOOP;
  --
  -- convert base64 CLOB to BLOB (mimetype: image/png)
  l_blob := apex_web_service.clobbase642blob(p_clob => l_clob);

  INSERT INTO cc.ibs_emp_signature
    (ibs_no,
     emp_signature,
     bosta_id)
  VALUES
    (6655,
     l_blob,
     4455);
END;
```

`

**Comment by Dani3lSun** [comment]
Hi @ehabwagdy 

yeah also possible, therefore I commented "create own collection (here starts custom part (for example a Insert statement))" in the code!:)
So you can remove all apex collection stuff and only the insert statement persists...Important is the code that builds the base64 clob and then converts to blob, after that you can do whatever you want with this blob...

Can I close this issue then?

Best wishes
Daniel

**Comment by ehabwagdy** [comment]
Dear Daniel

thanks for your effort and support

but i did that but i want to get value from field item in other region ?
how i can do that ?

thanks

**Comment by Dani3lSun** [comment]
Therefore I wrote in my first post over the Event "Signature saved to DB" Method. There you can specify "Page Items to Submit" just beyond the PL/SQL Code area. And then you can use these items in you PL/SQL code...
If you choose this method, I would let the original plsql code from the plugin stay untouched, and do it like I wrote in the first post...

**Comment by ehabwagdy** [comment]
Dear Daniel

in the first sorry for sending many times

in the following my code

DECLARE
  --
  l_collection_name VARCHAR2(100);
  l_clob            CLOB;
  l_blob            BLOB;
  l_filename        VARCHAR2(100);
  l_mime_type       VARCHAR2(100);
  l_token           VARCHAR2(32000);
  --
BEGIN
  -- get defaults
  l_filename  := 'signature_' ||
                 to_char(SYSDATE,
                         'YYYYMMDDHH24MISS') || '.png';
  l_mime_type := 'image/png';
  -- build CLOB from f01 30k Array
  dbms_lob.createtemporary(l_clob,
                           FALSE,
                           dbms_lob.session);

  FOR i IN 1 .. apex_application.g_f01.count LOOP
    l_token := wwv_flow.g_f01(i);

```
IF length(l_token) > 0 THEN
  dbms_lob.writeappend(l_clob,
                       length(l_token),
                       l_token);
END IF;
```

  END LOOP;
  --
  -- convert base64 CLOB to BLOB (mimetype: image/png)
  l_blob := apex_web_service.clobbase642blob(p_clob => l_clob);
  --

  INSERT INTO cc.ibs_emp_signature
    (ibs_no,
     emp_signature,
     bosta_id)
  VALUES
-    (:P9_NEW,*
   l_blob,--l_rec_signature.img_content,
   4455);
  -- delete original collection
  -- apex_collection.delete_collection(p_collection_name =>
  'APEX_SIGNATURE');
  
  ## 
  
  END;

after insert the "ibs_no" column  be empty are is a wrong way to get the
item value ?

thanks for your support and waiting your feedback

**Comment by Dani3lSun** [comment]
This only works if the value of P9_NEW does not change at runtime (and has already a value at page load), if this item changes you have to go the other way with a separate DA with Event "Signature saved to DB" as described above...

Hope this helps!;)

**Comment by ehabwagdy** [comment]
many thanks it's working

sorry for send many mails to you. you are supported me very well.

**Comment by rv8470** [comment]
Hello,
Is it possible to make the plug-in optional? It is now mandatory
Thanks

**Comment by nigah35** [comment]
Hi Daniel,

Hope you are doing good.

I am using your apex signature plugin and it's been really helpful. Thanks for being a person for making this world a better place by sharing knowledge.

I was looking into how we can modify the plugin or its settings so the images stored in the table are jpg and not png? I'll appreciate your help and have my gratitude in advance.

Thanks!
