### ISSUE TITLE
Attribute "Page Items to Submit" not working

### ISSUE THREAD

**Issue by kashography** [Dani3lSun/apex-plugin-apexsignature#2]
### Expected behavior
Chose an Item to Submit, which i'd like to insert into the same table when writing the blob-signature.

### Actual behavior
Session-State of the item remains empty when no manual page submit or pl/sql-submit executed

### Steps to reproduce the issue
I marked the checkbox for "items to submit" in the plugin attributes. then filled in the item on the region.

### APEX version (4.2.6 / 5.0.3)
5.0.2

### Used web server / version and platform (ORDS 3.0.3 / Tomcat 7 / Apache 2.4 / Linux x64)
Ords 3.0.8

### Used web browser / version and platform (Chrome 48 Mac / Firefox 44 Windows)
Firefox/Chrome

Thanks for this plugin. Works great!

**Comment by Dani3lSun** [comment]
Hi @kashography 
the plugin doesn´t have this attribute.
You can´t go to Shared Components --> Plugins and activate this setting by yourself. This has to be done by the plugin developer thus this setting has to be used in the Javascript and PL/SQL code of the plugin...
Nevertheless I think you would do an insert into your own table with additional information which are coming out of page items,. is this right?

**Comment by kashography** [comment]
Hi Dani3lSun
Sorry for my late answer. Yes I want to write Page Items (that were not submitted before) to the same table as the signature. Now i had to do a workarround where i used a dummy-"Save"button that saves the value to the session states and then triggers the button that your are listening on with the plugin
