### ISSUE TITLE
Is it compatible with apex mobile application?

### ISSUE THREAD

**Issue by Farzanah1808** [Dani3lSun/apex-plugin-apexsignature#3]
Hello,
     this is a nice plugin. Is it compatible with the apex mobile application?

**Comment by Dani3lSun** [comment]
Hey @Farzanah1808 
I have not tested it and it is not enabled in the plugin settings but you can try...I think it should work in mobile applications as well...
If you would like that the plugin is listed under "supported" than you have to tick a checkbox in the plugin settings (shared components / plugins):
<img width="959" alt="create___edit_plug-in" src="https://user-images.githubusercontent.com/698942/28590118-46abfd5c-7181-11e7-8af0-abe4dc8b57aa.png">
