### ISSUE TITLE
Output to JPG

### ISSUE THREAD

**Issue by ghost** [Dani3lSun/apex-plugin-apexsignature#5]
### Expected behavior
I would like the plugin to output the signature to JPG instead of PNG.

### Actual behavior
Seems like the default when saving the BLOB is PNG.

### Steps to reproduce the issue
Take the normal steps and save to the DB using a simple insert statement.

### APEX version (4.2.6 / 5.0.3)
18.1.0.00.45

### Used web server / version and platform (ORDS 3.0.3 / Tomcat 7 / Apache 2.4 / Linux x64)
ORDS

### Used web browser / version and platform (Chrome 48 Mac / Firefox 44 Windows)
Chrome latest

### Question
I am sure that I missed this setting somewhere, but is it possible to have the plugin output a JPG/BLOB instead of PNG?

**Comment by mathiasmaciel97** [comment]
Hi there!

Did you solve this?

I want to be able to save it as jpg file.

Regards,
Mathias
